---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "simple-client"
  replicas: 3
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "simple-client"
    spec:
      serviceAccount: nsc-acc
      containers:
        - name: alpine-img
          image: alpine:latest
          imagePullPolicy: IfNotPresent
          command: ["sh", "-f", "/client-init/client-init"]
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /client-init
              name: client-init
      volumes:
        - name: client-init
          configMap:
            name: client-init

metadata:
  name: simple-client
  namespace: default
  annotations:
    ns.networkservicemesh.io: load-balancer?app=lb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-init
data:
  client-init: |
    ip addr add 10.2.2.0/24 dev lo
    ip link set up dev gre0
    ip ro add 10.70.0.0/31 via 10.60.1.1
    ip ro add 33.0.0.0/24 via 10.60.1.1
    nc -lk -p 5001 -e hostname
