---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "simple-client"
  replicas: 3
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "simple-client"
    spec:
      serviceAccount: nsc-acc
      containers:
        - name: alpine-img
          image: alpine:latest
          imagePullPolicy: IfNotPresent
          command: ["tail", "-f", "/dev/null"]
          securityContext:
            privileged: true
        - name: mconnect
          image: docker.io/nordixorg/mconnect:v1.2
metadata:
  name: simple-client
  namespace: default
  annotations:
    ns.networkservicemesh.io: load-balancer?app=lb
